<template>
  <div class="bg-grey">
    <header class="top-bar">
      <div class="container header-padding">
        <div class="row">
          <div class="col-12">
            <div class="inline-block">
              <router-link to="/settings">
                <img
                  class="img-fluid back-arrow float-left"
                  src="@/assets/images/select-players/back-arrow.svg"
                  alt="arrow"
                >
              </router-link>
              <h3 class="text-center header-title">PRIVACY</h3>
            </div>
          </div>
        </div>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-12 mt">
          <img
            class="img-fluid mr float-left"
            src="@/assets/images/leagues/logo-ball.svg"
            alt="logo ball"
          >
          <h3 class="mt">
            <strong>PRIVACY POLICY</strong>
          </h3>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-12 bmt">
          <p>
            Fantasy Football Scotland ("us", "we", or "our") operates the Fantasy Football
            Scotland mobile application (hereinafter referred to as the "Service").
          </p>
          <p>
            This page informs you of our policies regarding the collection, use and
            disclosure of personal data when you use our Service and the choices you have
            associated with that data.
          </p>
          <p>
            We use your data to provide and improve the Service. By using the Service, you
            agree to the collection and use of information in accordance with this policy.
            Unless otherwise defined in this Privacy Policy, the terms used in this
            Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>
          <h3 class>Definitions</h3>
          <p>* Service</p>
          <p>
            Service is the Fantasy Football Scotland mobile application operated by
            Fantasy Football Scotland
          </p>
          <p>* Personal Data</p>
          <p>
            Personal Data means data about a living individual who can be identified
            from those data (or from those and other information either in our
            possession or likely to come into our possession).
          </p>
          <p>* Usage Data</p>
          <p>
            Usage Data is data collected automatically either generated by the use of
            the Service or from the Service infrastructure itself (for example, the
            duration of a page visit).
          </p>
          <p>* Cookies</p>
          <p>
            Cookies are small files stored on your device (computer or mobile
            device).
          </p>
          <p>* Data Controller</p>
          <p>
            Data Controller means the natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal information are, or are to be,
            processed. For the purpose of this Privacy Policy, we are a Data Controller of your
            Personal Data.
          </p>
          <p>* Data Processors (or Service Providers)</p>
          <p>
            Data Processor (or Service Provider) means any natural or legal person
            who processes the data on behalf of the Data Controller.
          </p>
          <p>
            We may use the services of various Service Providers in order to process
            your data more effectively.
          </p>

          <p>* Data Subject (or User)</p>
          <p>
            Data Subject is any living individual who is using our Service and is the
            subject of Personal Data.
          </p>

          <h3 class>Information Collection and Use</h3>
          <p>
            We collect several different types of information for various purposes to
            provide and improve our Service to you.
          </p>
          <h3 class>Types of Data Collected</h3>
          <p>
            Personal Data
            *************
          </p>
          <p>
            While using our Service, we may ask you to provide us with certain personally
            identifiable information that can be used to contact or identify you
            ("Personal Data"). Personally identifiable information may include, but is not
            limited to:
            * Email address
            * First name and last name
            * Cookies and Usage Data
            We may use your Personal Data to contact you with newsletters, marketing or
            promotional materials and other information that may be of interest to you.
            You may opt out of receiving any, or all, of these communications from us by
            contacting us.
          </p>
          <p>
            Usage Data
            **********
          </p>
          <p>
            When you access the Service with a mobile device, we may collect certain
            information automatically, including, but not limited to, the type of mobile
            device you use, your mobile device unique ID, the IP address of your mobile
            device, your mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data ("Usage Data").
          </p>
          <p>
            Tracking & Cookies Data
            ************
          </p>
          <p>
            We use cookies and similar tracking technologies to track the activity on our
            Service and we hold certain information.
          </p>
          <p>
            Cookies are files with a small amount of data which may include an anonymous
            unique identifier. Cookies are sent to your browser from a website and stored
            on your device. Other tracking technologies are also used such as beacons,
            tags and scripts to collect and track information and to improve and analyse
            our Service.
          </p>
          <p>Examples of Cookies we use:</p>
          <p>
            * Session Cookies. We use Session Cookies to operate our Service.
            * Preference Cookies. We use Preference Cookies to remember your preferences
            and various settings.
            * Security Cookies. We use Security Cookies for security purposes.
          </p>
          <h3>Use of Data</h3>
          <p>Fantasy Football Scotland uses the collected data for various purposes:</p>

          <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>
              To allow you to participate in interactive features of our Service when
              you choose to do so
            </li>
            <li>To provide customer support</li>
            <li>
              To gather analysis or valuable information so that we can improve our
              Service
            </li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>
              To provide you with news, special offers and general information about
              other goods, services and events which we offer that are similar to those
              that you have already purchased or enquired about unless you have opted
              not to receive such information
            </li>
          </ul>

          <p>
            Legal Basis for Processing Personal Data under the General Data Protection
            Regulation (GDPR)
            --------------------------------------------------------------------------------------------
          </p>
          <p>
            If you are from the European Economic Area (EEA), Fantasy Football Scotland
            legal basis for collecting and using the personal information described in
            this Privacy Policy depends on the Personal Data we collect and the specific
            context in which we collect it.
          </p>

          <p>Fantasy Football Scotland may process your Personal Data because:</p>
          <ul>
            <li>We need to perform a contract with you</li>
            <li>You have given us permission to do so</li>
            <li>
              The processing is in our legitimate interests and it is not overridden by
              your rights
            </li>
            <li>To comply with the law</li>
          </ul>
          <p>
            Retention of Data
            -----------------
          </p>
          <p>
            Fantasy Football Scotland will retain your Personal Data only for as long as
            is necessary for the purposes set out in this Privacy Policy. We will retain
            and use your Personal Data to the extent necessary to comply with our legal
            obligations (for example, if we are required to retain your data to comply
            with applicable laws), resolve disputes and enforce our legal agreements and
            policies.
          </p>
          <p>
            Fantasy Football Scotland will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of time,
            except when this data is used to strengthen the security or to improve the
            functionality of our Service, or we are legally obligated to retain this data
            for longer periods.
          </p>
          <p>
            Transfer of Data
            ----------------
          </p>
          <p>
            Your information, including Personal Data, may be transferred to — and
            maintained on — computers located outside of your state, province, country or
            other governmental jurisdiction where the data protection laws may differ from
            those of your jurisdiction.
          </p>
          <p>
            If you are located outside United Kingdom and choose to provide information to
            us, please note that we transfer the data, including Personal Data, to United
            Kingdom and process it there.
          </p>
          <p>
            Your consent to this Privacy Policy followed by your submission of such
            information represents your agreement to that transfer.
          </p>
          <p>
            Fantasy Football Scotland will take all the steps reasonably necessary to
            ensure that your data is treated securely and in accordance with this Privacy
            Policy and no transfer of your Personal Data will take place to an
            organisation or a country unless there are adequate controls in place
            including the security of your data and other personal information.
          </p>
          <p>
            Disclosure of Data
            ------------------
          </p>
          <p>
            Disclosure for Law Enforcement
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          </p>
          <p>
            Under certain circumstances, Fantasy Football Scotland may be required to
            disclose your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government agency).
          </p>
          <p>
            Legal Requirements
            ~~~~~~~~~~~~~~~~~~
          </p>
          <p>
            Fantasy Football Scotland may disclose your Personal Data in the good faith
            belief that such action is necessary to:
          </p>
          <ul>
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Fantasy Football Scotland</li>
            <li>
              To prevent or investigate possible wrongdoing in connection with the
              Service
            </li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
          </ul>
          <p>
            Security of Data
            ----------------
          </p>
          <p>
            The security of your data is important to us but remember that no method of
            transmission over the Internet or method of electronic storage is 100% secure.
            While we strive to use commercially acceptable means to protect your Personal
            Data, we cannot guarantee its absolute security.
          </p>
          <p>
            Your Data Protection Rights under the General Data Protection Regulation
            (GDPR)
            -------------------------------------------------------------------------------
          </p>
          <p>
            If you are a resident of the European Economic Area (EEA), you have certain
            data protection rights. Fantasy Football Scotland aims to take reasonable
            steps to allow you to correct, amend, delete or limit the use of your Personal
            Data.
          </p>
          <p>
            If you wish to be informed about what Personal Data we hold about you and if
            you want it to be removed from our systems, please contact us.
          </p>
          <p>In certain circumstances, you have the following data protection rights:</p>
          <ul>
            <li>
              The right to access, update or delete the information we have on you.
              Whenever made possible, you can access, update or request deletion of your
              Personal Data directly within your account settings section. If you are
              unable to perform these actions yourself, please contact us to assist you.
            </li>
            <li>
              The right of rectification. You have the right to have your information
              rectified if that information is inaccurate or incomplete.
            </li>
            <li>
              The right to object. You have the right to object to our processing of
              your Personal Data.
            </li>
            <li>
              The right of restriction. You have the right to request that we restrict
              the processing of your personal information.
            </li>
            <li>
              The right to data portability. You have the right to be provided with a
              copy of the information we have on you in a structured, machine-readable
              and commonly used format.
            </li>
            <li>
              The right to withdraw consent. You also have the right to withdraw your
              consent at any time where Fantasy Football Scotland relied on your consent
              to process your personal information.
              Please note that we may ask you to verify your identity before responding to
              such requests.
            </li>
          </ul>
          <p>
            You have the right to complain to a Data Protection Authority about our
            collection and use of your Personal Data. For more information, please contact
            your local data protection authority in the European Economic Area (EEA).
          </p>
          <p>
            Service Providers
            -----------------
          </p>
          <p>
            We may employ third party companies and individuals to facilitate our Service
            ("Service Providers"), provide the Service on our behalf, perform Service-
            related services or assist us in analysing how our Service is used.
            These third parties have access to your Personal Data only to perform these
            tasks on our behalf and are obligated not to disclose or use it for any other
            purpose.
          </p>
          <p>
            Analytics
            ~~~~~~~~~
          </p>
          <p>
            We may use third-party Service Providers to monitor and analyse the use of our
            Service.
          </p>
          <p>* Google Analytics</p>
          <p>
            Google Analytics is a web analytics service offered by Google that tracks
            and reports website traffic. Google uses the data collected to track and
            monitor the use of our Service. This data is shared with other Google
            services. Google may use the collected data to contextualise and
            personalise the ads of its own advertising network.
          </p>
          <p>
            You may opt-out of certain Google Analytics features through your mobile
            device settings, such as your device advertising settings or by following
            the instructions provided by Google in their Privacy Policy:
          </p>
          <p>
            <a href="https://policies.google.com/privacy?hl=en">Google Provacy Policy</a>
          </p>
          <p>
            For more information on the privacy practices of Google, please visit the
            Google Privacy & Terms web page:
          </p>
          <p>
            <a href="https://policies.google.com/privacy?hl=en">Google Provacy Policy</a>
          </p>
          <p>
            Links to Other Sites
            --------------------
          </p>
          <p>
            Our Service may contain links to other sites that are not operated by us. If
            you click a third party link, you will be directed to that third party's site.
            We strongly advise you to review the Privacy Policy of every site you visit.
            We have no control over and assume no responsibility for the content, privacy
            policies or practices of any third party sites or services.
          </p>
          <p>
            Children's Privacy
            ------------------
          </p>
          <p>
            Our Service does not address anyone under the age of 18 ("Children").
            We do not knowingly collect personally identifiable information from anyone
            under the age of 18. If you are a parent or guardian and you are aware that
            your Child has provided us with Personal Data, please contact us. If we become
            aware that we have collected Personal Data from children without verification
            of parental consent, we take steps to remove that information from our
            servers.
          </p>
          <p>
            Changes to This Privacy Policy
            ------------------------------
          </p>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any
            changes by posting the new Privacy Policy on this page.
            We will let you know via email and/or a prominent notice on our Service, prior
            to the change becoming effective and update the "effective date" at the top of
            this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any changes.
            Changes to this Privacy Policy are effective when they are posted on this
            page.
          </p>
          <p>
            Contact Us
            ----------
          </p>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <p>* By email: welcome@fantasyfootballscotland.com</p>

          <p>
            This page informs you of our policies regarding the collection, use and
            disclosure of personal data when you use our Service and the choices you have
            associated with that data.
          </p>
          <p>
            We use your data to provide and improve the Service. By using the Service, you
            agree to the collection and use of information in accordance with this policy.
            Unless otherwise defined in this Privacy Policy, the terms used in this
            Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>
          <h3 class>Definitions</h3>
          <p>* Service</p>
          <p>
            Service is the Fantasy Football Scotland mobile application operated by
            Fantasy Football Scotland
          </p>
          <p>* Personal Data</p>
          <p>
            Personal Data means data about a living individual who can be identified
            from those data (or from those and other information either in our
            possession or likely to come into our possession).
          </p>
          <p>* Usage Data</p>
          <p>
            Usage Data is data collected automatically either generated by the use of
            the Service or from the Service infrastructure itself (for example, the
            duration of a page visit).
          </p>
          <p>* Cookies</p>
          <p>
            Cookies are small files stored on your device (computer or mobile
            device).
          </p>
          <p>* Data Controller</p>
          <p>
            Data Controller means the natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal information are, or are to be,
            processed. For the purpose of this Privacy Policy, we are a Data Controller of your
            Personal Data.
          </p>
          <p>* Data Processors (or Service Providers)</p>
          <p>
            Data Processor (or Service Provider) means any natural or legal person
            who processes the data on behalf of the Data Controller.
          </p>
          <p>
            We may use the services of various Service Providers in order to process
            your data more effectively.
          </p>

          <p>* Data Subject (or User)</p>
          <p>
            Data Subject is any living individual who is using our Service and is the
            subject of Personal Data.
          </p>

          <h3 class>Information Collection and Use</h3>
          <p>
            We collect several different types of information for various purposes to
            provide and improve our Service to you.
          </p>
          <h3 class>Types of Data Collected</h3>
          <p>
            Personal Data
            *************
          </p>
          <p>
            While using our Service, we may ask you to provide us with certain personally
            identifiable information that can be used to contact or identify you
            ("Personal Data"). Personally identifiable information may include, but is not
            limited to:
            * Email address
            * First name and last name
            * Cookies and Usage Data
            We may use your Personal Data to contact you with newsletters, marketing or
            promotional materials and other information that may be of interest to you.
            You may opt out of receiving any, or all, of these communications from us by
            contacting us.
          </p>
          <p>
            Usage Data
            **********
          </p>
          <p>
            When you access the Service with a mobile device, we may collect certain
            information automatically, including, but not limited to, the type of mobile
            device you use, your mobile device unique ID, the IP address of your mobile
            device, your mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data ("Usage Data").
          </p>
          <p>
            Tracking & Cookies Data
            ************
          </p>
          <p>
            We use cookies and similar tracking technologies to track the activity on our
            Service and we hold certain information.
          </p>
          <p>
            Cookies are files with a small amount of data which may include an anonymous
            unique identifier. Cookies are sent to your browser from a website and stored
            on your device. Other tracking technologies are also used such as beacons,
            tags and scripts to collect and track information and to improve and analyse
            our Service.
          </p>
          <p>Examples of Cookies we use:</p>
          <p>
            * Session Cookies. We use Session Cookies to operate our Service.
            * Preference Cookies. We use Preference Cookies to remember your preferences
            and various settings.
            * Security Cookies. We use Security Cookies for security purposes.
          </p>

          <h3>Use of Data</h3>
          <p>Fantasy Football Scotland uses the collected data for various purposes:</p>

          <ul>
            <li>* To provide and maintain our Service</li>
            <li>* To notify you about changes to our Service</li>
            <li>
              * To allow you to participate in interactive features of our Service when
              you choose to do so
            </li>
            <li>* To provide customer support</li>
            <li>
              * To gather analysis or valuable information so that we can improve our
              Service
            </li>
            <li>* To monitor the usage of our Service</li>
            <li>* To detect, prevent and address technical issues</li>
            <li>
              * To provide you with news, special offers and general information about
              other goods, services and events which we offer that are similar to those
              that you have already purchased or enquired about unless you have opted
              not to receive such information
            </li>
          </ul>

          <p>
            Legal Basis for Processing Personal Data under the General Data Protection
            Regulation (GDPR)
          </p>
            --------------------------------------------------------------------------------------------
           <p> If you are from the European Economic Area (EEA), Fantasy Football Scotland
            legal basis for collecting and using the personal information described in
            this Privacy Policy depends on the Personal Data we collect and the specific
            context in which we collect it.</p>

            <p>Fantasy Football Scotland may process your Personal Data because:
            * We need to perform a contract with you
            * You have given us permission to do so
            * The processing is in our legitimate interests and it is not overridden by
            your rights
            * To comply with the law
            </p>
            <p>
            Retention of Data
            </p>
            <p>
            -----------------
            </p>
            <p>Fantasy Football Scotland will retain your Personal Data only for as long as
            is necessary for the purposes set out in this Privacy Policy. We will retain
            and use your Personal Data to the extent necessary to comply with our legal
            obligations (for example, if we are required to retain your data to comply
            with applicable laws), resolve disputes and enforce our legal agreements and
            policies.</p>
            <p>Fantasy Football Scotland will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of time,
            except when this data is used to strengthen the security or to improve the
            functionality of our Service, or we are legally obligated to retain this data
            for longer periods.</p>
            <p>Transfer of Data</p>
            <p>----------------</p>
            <p>Your information, including Personal Data, may be transferred to — and
            maintained on — computers located outside of your state, province, country or
            other governmental jurisdiction where the data protection laws may differ from
            those of your jurisdiction.
            </p><p>If you are located outside United Kingdom and choose to provide information to
            us, please note that we transfer the data, including Personal Data, to United
            Kingdom and process it there.
            </p><p>Your consent to this Privacy Policy followed by your submission of such
            information represents your agreement to that transfer.
            </p><p>Fantasy Football Scotland will take all the steps reasonably necessary to
            ensure that your data is treated securely and in accordance with this Privacy
            Policy and no transfer of your Personal Data will take place to an
            organisation or a country unless there are adequate controls in place
            including the security of your data and other personal information.
            </p><p>Disclosure of Data
            </p><p>------------------
            </p><p>Disclosure for Law Enforcement
            </p><p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            </p><p>Under certain circumstances, Fantasy Football Scotland may be required to
            disclose your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government agency).
            </p><p>Legal Requirements
            </p><p>~~~~~~~~~~~~~~~~~~
            </p><p>Fantasy Football Scotland may disclose your Personal Data in the good faith
            belief that such action is necessary to:
            * To comply with a legal obligation
            * To protect and defend the rights or property of Fantasy Football Scotland
            * To prevent or investigate possible wrongdoing in connection with the
            Service
            * To protect the personal safety of users of the Service or the public
            * To protect against legal liability
            </p><p>Security of Data
            </p><p>----------------
            </p><p>The security of your data is important to us but remember that no method of
            transmission over the Internet or method of electronic storage is 100% secure.
            While we strive to use commercially acceptable means to protect your Personal
            Data, we cannot guarantee its absolute security.
            </p><p>Your Data Protection Rights under the General Data Protection Regulation
            (GDPR)
            </p><p>-------------------------------------------------------------------------------
            </p><p>If you are a resident of the European Economic Area (EEA), you have certain
            data protection rights. Fantasy Football Scotland aims to take reasonable
            steps to allow you to correct, amend, delete or limit the use of your Personal
            Data.
            </p><p>If you wish to be informed about what Personal Data we hold about you and if
            you want it to be removed from our systems, please contact us.
            </p><p>In certain circumstances, you have the following data protection rights:
            * The right to access, update or delete the information we have on you.
            </p><p>Whenever made possible, you can access, update or request deletion of your
            Personal Data directly within your account settings section. If you are
            unable to perform these actions yourself, please contact us to assist you.
            * The right of rectification. You have the right to have your information
            rectified if that information is inaccurate or incomplete.
            * The right to object. You have the right to object to our processing of
            your Personal Data.
            * The right of restriction. You have the right to request that we restrict
            the processing of your personal information.
            * The right to data portability. You have the right to be provided with a
            copy of the information we have on you in a structured, machine-readable
            and commonly used format.
            * The right to withdraw consent. You also have the right to withdraw your
            consent at any time where Fantasy Football Scotland relied on your consent
            to process your personal information.
            </p><p>Please note that we may ask you to verify your identity before responding to
            such requests.
            </p><p>You have the right to complain to a Data Protection Authority about our
            collection and use of your Personal Data. For more information, please contact
            your local data protection authority in the European Economic Area (EEA).
            </p><p>Service Providers
            </p><p>-----------------
            </p><p>We may employ third party companies and individuals to facilitate our Service
            ("Service Providers"), provide the Service on our behalf, perform Service-
            related services or assist us in analysing how our Service is used.
            These third parties have access to your Personal Data only to perform these
            tasks on our behalf and are obligated not to disclose or use it for any other
            purpose.
            </p><p>Analytics
            </p><p>~~~~~~~~~
            </p><p>We may use third-party Service Providers to monitor and analyse the use of our
            Service.
            * Google Analytics
            </p><p>Google Analytics is a web analytics service offered by Google that tracks
            and reports website traffic. Google uses the data collected to track and
            monitor the use of our Service. This data is shared with other Google
            services. Google may use the collected data to contextualise and
            personalise the ads of its own advertising network.
            </p><p>You may opt-out of certain Google Analytics features through your mobile
            device settings, such as your device advertising settings or by following
            the instructions provided by Google in their Privacy Policy:
            <a
              href="https://policies.google.com/privacy?hl=en"
            >Google Provacy Policy</a>
            </p><p>For more information on the privacy practices of Google, please visit the
            Google Privacy & Terms web page:
            <a
              href="https://policies.google.com/privacy?hl=en"
            >Google Provacy Policy</a>

            </p><p>Links to Other Sites
            </p><p>--------------------
            </p><p>Our Service may contain links to other sites that are not operated by us. If
            you click a third party link, you will be directed to that third party's site.
            We strongly advise you to review the Privacy Policy of every site you visit.
            We have no control over and assume no responsibility for the content, privacy
            policies or practices of any third party sites or services.
            </p><p>Children's Privacy
            </p><p>------------------
            </p><p>Our Service does not address anyone under the age of 18 ("Children").
            </p><p>We do not knowingly collect personally identifiable information from anyone
            under the age of 18. If you are a parent or guardian and you are aware that
            your Child has provided us with Personal Data, please contact us. If we become
            aware that we have collected Personal Data from children without verification
            of parental consent, we take steps to remove that information from our
            servers.
            </p><p>Changes to This Privacy Policy
            </p><p>------------------------------
            </p><p>We may update our Privacy Policy from time to time. We will notify you of any
            changes by posting the new Privacy Policy on this page.
            We will let you know via email and/or a prominent notice on our Service, prior
            to the change becoming effective and update the "effective date" at the top of
            this Privacy Policy.
            </p><p>You are advised to review this Privacy Policy periodically for any changes.
            Changes to this Privacy Policy are effective when they are posted on this
            page.
            </p><p>Contact Us
            </p><p>----------
            </p><p>If you have any questions about this Privacy Policy, please contact us:
            * By email: welcome@fantasyfootballscotland.com</p>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>
<script type="text/javascript">
import Auth from "../assets/store/auth";
import { get, post } from "../assets/helpers/api";
import Status from "../assets/helpers/status";
export default {
  beforeMount() {},
  created() {
    if (Auth.state.api_token !== "" && Auth.state.api_token !== null) {
      //this.$router.push({path: '/settings'});
    } else {
      Auth.set("", "", "");
      this.$router.push({ path: "/login" });
    }
    if (Auth.state.error) {
      this.error = Auth.state.error.includes("+")
        ? Auth.state.error.replace(/\+/gi, " ")
        : Auth.state.error;
    }
  },
  computed: {},
  data() {
    return {
      form: {
        email: "",
        password: ""
      },
      error: {},
      isProcessing: false,
      auth: null,
      status: null
    };
  },
  methods: {
    login() {
      this.isProcessing = true;
      this.error = {};
      post("https://backend.fantasyfootballscotland.com/api/login", this.form)
        .then(response => {
          if (response.data.authenticated) {
            Auth.set(
              response.data.api_token,
              response.data.user_id,
              response.data.site_settings
            );
            Status.setSuccess("You have successfully logged in!");

            this.flashMessage.success({
              title: "Logged In: success",
              message: "",
              time: 3000,
              flashMessageStyle: {
                backgroundColor: "linear-gradient(#e66465, #9198e5)"
              }
            });

            this.auth = Auth;
            this.status = Status;
            setTimeout(
              function() {
                this.$router.push({ path: "/createteam" });
              }.bind(this),
              2000
            );
          }
          this.isProcessing = false;
        })
        .catch(err => {
          if (err.response.data.code === 422 && err.response.data.error) {
            console.log("inside here");
            //if(err.response.data.error){
            //this.error = err.response.data.errors;

            this.flashMessage.error({
              title: "Error",
              message: err.response.data.error,
              time: 5000,
              flashMessageStyle: {
                backgroundColor: "linear-gradient(#e66465, #9198e5)"
              }
            });
          }
          this.isProcessing = false;
        });
    },
    logout() {
      Auth.set("", "", "");
      get("https://backend.fantasyfootballscotland.com/api/logout")
        .then(response => {
          if (response.data.logged_out) {
            Auth.set("", "", "");
            Auth.remove();
            this.$router.push({ path: "/login" });
          }
        })
        .catch(err => {
          Auth.set("", "", "");
          Auth.remove();
          this.$router.push({ path: "/login" });
        });
    }
  }
};
</script>

<style>
h2, h3{
  text-transform: capitalize !important ; 
}
</style>